### ISSUE TITLE
Swift bytes_up/bytes_down statistics seem to be global

### ISSUE THREAD

**Issue by NielsZeilemaker** [libswift/libswift#1]
While testing new SeedingManager for Swift it seems that both bytes_up and bytes_down as reported by Swift in the moreinfo message are global instead of the expected totals per swarm.

**Comment by synctext** [comment]
From a GUI or BarterCast3 perspective I don't see a preference directly for per swarm or global stats.

But I guess the intuition of most people would be per swarms stats, so anything else requires explicit documentation.
