### ISSUE TITLE
Rename and format README to README.md

### ISSUE THREAD

**Issue by whirm** [libswift/libswift#2]
This should be made _after_ we finish moving to GH in case the README gets updated on svn in the meanwhile.

**Comment by whirm** [comment]
I think Riccardo wanted to update some documentation on swift, maybe he would be the guy to do this?

**Comment by badrock** [comment]
Done.. Obviously still needs to be updated with a better content

**Comment by whirm** [comment]
@badrock Take in mind that it's currently only on the devel branch, so it doesn't show when visiting the repo main page.
