### ISSUE TITLE
Swift is printing some debug info to stderr by default

### ISSUE THREAD

**Issue by NielsZeilemaker** [libswift/libswift#33]
swarmmanager.cpp AddSwarm:

```
fprintf(stderr,"swarmmgr: AddSwarm: ConnectToTracker\n");
```

swift.cpp wWinMain:

```
fprintf(stderr,"wWinMain: enter\n");
```

Can we remove these/put them behind a debug flag?

**Comment by LipuFei** [comment]
I guess no. Swift is not using any logging library.

**Comment by NielsZeilemaker** [comment]
Can you have a go?

**Comment by LipuFei** [comment]
I'm not very familiar with C++ logging libraries. Perhaps we can use boost or log4cxx, but I think we may ask @whirm before we start converting everything.

**Comment by NielsZeilemaker** [comment]
I didn't mean upgrading the logging, I was thinking maybe add the if (!quiet) stuff in from of those.

**Comment by LipuFei** [comment]
No problem.

**Comment by badrock** [comment]
see merge #39
