### ISSUE TITLE
Cmdgw, start command without tracker

### ISSUE THREAD

**Issue by VincentKetelaars** [libswift/libswift#41]
In earlier versions it was possible to start a download without supplying a tracker. This is no longer possible as far as I understand.

https://github.com/libswift/libswift/blob/devel/cmdgw.cpp, from line 786

However I presume it should still be possible to start a download without a tracker?

**Comment by badrock** [comment]
@VincentKetelaars Not really. You need to know at least a peer (or tracker)  to start a new download.
Otherwise you can always start it if the content is already available, hence you don't need a peer/tracker.
