### ISSUE TITLE
Adding mac homebrew support

### ISSUE THREAD

**Issue by dch** [libswift/libswift#46]
Hi,

If you can add a tag to a recent commit then it's possible for people to install swift on OSX via homebrew `brew install swift`. Currently they no longer accept head-only formulae so a git tag is the way to go. See https://github.com/Homebrew/homebrew/pull/30764#issuecomment-48479123 for a little more info.

**Comment by dch** [comment]
bump, can we have a tag please?

**Comment by whirm** [comment]
@badrock I can do it if you are too busy.

**Comment by badrock** [comment]
@dch Sorry for the late reply.
@whirm now merging the last changes to the congestion control and will create a new tag.

**Comment by dch** [comment]
bump again .. 

![no-tags-please--large-msg-115894319859](https://cloud.githubusercontent.com/assets/284368/7391831/149bc59a-ee84-11e4-8e25-8a1c83517a42.jpg)

**Comment by badrock** [comment]
@dch sorry for the delay.. development of Libswift has been very slow lately.
I've created 2 releases:
- alpha: based on master, quite old but simple
- beta: with all the features from the draft and quite advanced

Both should be working (I haven't touched the master branch in a while).
Let me know if you have any issue.

**Comment by dch** [comment]
@badrock sweet thanks works as advertised.

BTW we have a bit of a naming conflict for OSX:
- swift is the new programming language from Apple
- libswiften is http://swift.im/swiften/

I suggest calling it libppspp if libswiften is not an option, unless you have a better suggestion?

**Comment by badrock** [comment]
@dch I know.. that was the initial reason for renaming it from swift to libswift.
Would libswift work?
