### ISSUE TITLE
Multi-file spec not working on Mac

### ISSUE THREAD

**Issue by LipuFei** [libswift/libswift#47]
Multi-file spec file should be in the following format:

```
<file-1> <size-of-file-1>
<file-2> <size-of-file-2>
...
```

On Mac OS X 10.8.5 (the Mac building machine), the spec file will also contain the actual file contents after those file description lines. As a result, we get 0-byte thumbnail files on Mac.

**Comment by LipuFei** [comment]
Found it. swift must be compiled with the `OPENSSL` macro defined, otherwise multispec will not work. The problem is the following lines in `swift.cpp`:

```
#ifndef OPENSSL
    swarm_cipm = POPT_CONT_INT_PROT_NONE;
#endif
```

And then when we invoke `Channel::OnHash()`, we will enter the first if-statement because `hs_in_->cont_int_prot_` and `hs_out_->cont_int_prot_` are 0. The if-statement is

```
if (hs_in_->cont_int_prot_ != POPT_CONT_INT_PROT_MERKLE
            && hs_in_->cont_int_prot_ != POPT_CONT_INT_PROT_UNIFIED_MERKLE) {
    ...
}
```

**Comment by badrock** [comment]
@LipuFei Yes, is known. No protection scheme is not supported at the moment.

**Comment by LipuFei** [comment]
@badrock #48 fixes it.

**Comment by badrock** [comment]
I've merged it.. but we need to look into a ./configure!
Again, had-coded library paths will be a problem in the future.. better solve it asap.
