### ISSUE TITLE
how to compile in win64  ?

### ISSUE THREAD

**Issue by hfmanly** [libswift/libswift#65]
F:\test\p2p\libswift-devel>win32-build.bat
svn: E155007: “F:\test\p2p\libswift-devel”不是工作副本
Error getting svn revision
系统找不到指定的路径。
系统找不到指定的文件。

Shanks

**Comment by LipuFei** [comment]
@hfmanly `win32-build.bat` calls `scons` to compile libswift. You need to install Python and the scons package, and make sure that `win32-build.bat` is calling `scons` in the right location.

BTW, you can also remove this line `svn-build-rev.py` to avoid the error `Error getting svn revision`.

**Comment by hfmanly** [comment]
that's ok when I have installed scons , libevent and openssl 

thank you
