### ISSUE TITLE
Can the option of  " -i, --source  live source input (URL or filename or - for stdin)"  do work?

### ISSUE THREAD

**Issue by hfmanly** [libswift/libswift#66]
my log:

F:\test\p2p\libswift-devel>swift -i http://192.168.109.186:8902/ -l 192.168.109.198:20000
swift: siglen is 64
live: http: Reading from serv 192.168.109.186 port 8902 path /
LiveTransfer::Initialize: cipm 3
LiveTransfer::Initialize: lsa  13
LiveTransfer::Initialize: ldw  4294967295
could not read live checkpoint file: No such file or directory
windows error #3
12: swift::print_backtrace - 0x12D2E70
11: swift::print_error - 0x12D2FF0
10: swift::LiveTransfer::ReadCheckpoint - 0x13145B0
9: swift::LiveTransfer::LiveTransfer - 0x1312CF0
8: swift::LiveCreate - 0x12D1630
7: HandleLiveSource - 0x12B5930
6: utf8main - 0x12B3090
5: wmain - 0x12B7200
4: __tmainCRTStartup - 0x1358870
3: wmainCRTStartup - 0x1358850
2: BaseThreadInitThunk - 0x75883378
1: RtlInitializeExceptionChain - 0x77BD9F0F
0: RtlInitializeExceptionChain - 0x77BD9F0F
live: source: restored lastchunkid 0
swift::LiveCreate: swarmid: 0da5991b8b1fde9617b9ef5d5f6f3ce227d37c1e14c9e38828702746bdae7e89c00efc43ed43d9da274efb1e81d91e899b5edf9aadf6fdf7e7a57d86fa34ca9ec2
swift::LiveCreate: ConnectToTracker
swift: Mainloop
live: http: read 3472 bytes
storage: cannot open single file: No such file or directory
windows error #3
7: swift::print_backtrace - 0x12D2E70
6: swift::print_error - 0x12D2FF0
5: swift::Storage::OpenSingleFile - 0x12FE4F0
4: swift::Storage::Write - 0x12FD2D0
3: swift::LiveTransfer::AddData - 0x13139E0
2: swift::LiveWrite - 0x12D1820
1: LiveSourceAttemptCreate - 0x12B7110
0: LiveSourceHTTPDownloadChunkCallback - 0x12B7090
live: create: error writing to storage: No such file or directory
5: swift::print_backtrace - 0x12D2E70
4: swift::print_error - 0x12D2FF0
3: swift::LiveTransfer::AddData - 0x13139E0
2: swift::LiveWrite - 0x12D1820
1: LiveSourceAttemptCreate - 0x12B7110
0: LiveSourceHTTPDownloadChunkCallback - 0x12B7090
live: http: read 4096 bytes

![pop_a_pic](https://cloud.githubusercontent.com/assets/4994187/8049581/943da8d4-0e93-11e5-8be5-da61ae24dd9d.jpg)

note: The http://192.168.109.186:8902/ is a ts live streaming , I can play it with vlc player
Using the file as input is ok, The following demo:
 F:\test\p2p\libswift-devel>swift -f g:\video\gyl.mp4  -l 192.168.109.198:20000
swift: parsedir: Opening g:\video\gyl.mp4
Root hash: 56f4734a4eda3db3b2147895b53b2a40bb949ee8
swift: Mainloop

BTW
My host is win7 64bit ,and the swift I compiled is 32bit  
Thanks

**Comment by synctext** [comment]
@hfmanly sadly we're no longer doing active development of Libswift. We're focussing full-time on the anonymous HD streaming of Tribler with the team. Sorry.

**Comment by LipuFei** [comment]
@hfmanly `Libswift` has some file-handling and memory management bugs. For example, the one you got is probably caused by using `fseek()` with an invalid file handle. Hope this gives you some help to debug it.

**Comment by hfmanly** [comment]
So, that is to say the Libswift can not use live streaming (such as  http://192.168.109.186:8902/ or rtmp://...  etc)  as source input  now ? 

Thank you

**Comment by synctext** [comment]
Live is supported. Try to run the live input source tests: https://github.com/libswift/libswift/blob/devel/tests/livetest.py
Should work.

**Comment by hfmanly** [comment]
You are right, thank you
