### ISSUE TITLE
Default SConstruct does not build on x64 windows or using SDK > V6.0A

### ISSUE THREAD

**Issue by Devristo** [libswift/libswift#7]
The default SConstruct file references the V6.0A Windows SDK by

C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib

However on x64 bit the SDKs are installed in:

C:\Program Files (x86)\Microsoft SDKs\Windows\

Even the 64 bit files are at that location. Also the more recent compatible SDK is versioned V7.1A. 

Ideally the SConstruct should only add existing paths, but adding 

`libpath += 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.1A\\Lib;'
libpath += 'C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1A\\Lib;'`

Will work as well

**Comment by whirm** [comment]
Yes, we need to improve SConstruct, it is not in a very good shape. Are you up for it?
